# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7d0ce6a9a2914c2fe80b57e47a5edaa2e96f6b0378ffd25f83bd87b96d46ea956080b3f1d027c92d63243b57a1baf91dcfe55fce6af12fd805bc44e007fede8

test:
  secret_key_base: ff2105ee9146596b0fbdc90f38e48305d6786bb21063ea1a477f2920f4485964f50e342766b9749966fa5e89d39c635e1e6a1bed54e01542ac300e873190e350

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
